-- =============================================
-- DACPAC Post-Deployment Script
-- Workflow: GM_PRC_DELIVERY
-- Rerunnable: YES.
-- Prerequisite: GM_TOTALS_CHECK seed must have run first.
--
-- Source files: output-files/{eventGuid}/TAR_ITM_GM_* and TAR_ITM_PRPC_*
--   (automatically generated by backend, same location TotalsValidationService uses)
-- Staging/Archive: flexcount-save
-- SFTP: /www.data/target-ssh/nexgen (from post-nexgen-gm-file script POSTDIR)
-- No conversion: NGen files zipped as-is (conversion commented out in scripts)
-- =============================================

DECLARE @id_Customer             INT;
DECLARE @id_CustomerWorkflowType INT;
DECLARE @id_Schedule             INT;
DECLARE @SftpConfig              NVARCHAR(500);

SET @id_Customer = (
    SELECT id_Customer FROM dbo.Customer
    WHERE  Name = 'TARGET FLEXCOUNT' AND is_Deleted = 0
);

IF @id_Customer IS NULL
BEGIN
    RAISERROR('TARGET FLEXCOUNT customer not found. Verify Name and is_Deleted=0.', 16, 1);
    RETURN;
END

IF NOT EXISTS (
    SELECT 1 FROM dbo.Pewo_CustomerWorkflowType
    WHERE  id_Customer = @id_Customer AND WorkflowType_Code = 'GM_TOTALS_CHECK'
)
BEGIN
    RAISERROR('GM_TOTALS_CHECK not found. Run PEWO_Seed_TARGET_GM_TOTALS_CHECK.sql first.', 16, 1);
    RETURN;
END

SET @SftpConfig = N'{"remotePath":"/www.data/target-ssh/nexgen","stagingContainer":"flexcount-save","idCustomer":' + CAST(@id_Customer AS NVARCHAR) + N'}';

-- ── 1. Pewo_CustomerWorkflowType ─────────────────────────────────────────────
IF EXISTS (
    SELECT 1 FROM dbo.Pewo_CustomerWorkflowType
    WHERE  id_Customer = @id_Customer AND WorkflowType_Code = 'GM_PRC_DELIVERY'
)
BEGIN
    SELECT @id_CustomerWorkflowType = id_CustomerWorkflowType
    FROM   dbo.Pewo_CustomerWorkflowType
    WHERE  id_Customer = @id_Customer AND WorkflowType_Code = 'GM_PRC_DELIVERY';
END
ELSE
BEGIN
    INSERT INTO dbo.Pewo_CustomerWorkflowType
        (id_Customer, WorkflowType_Code, WorkflowType_Name, Description,
         Max_Retries, is_Active, Fan_Out_Source_WorkflowType_Code,
         Fan_Out_Lookback_Hours, created_date, last_updated_date)
    VALUES
        (@id_Customer, 'GM_PRC_DELIVERY', 'TARGET GM + PRPC Delivery',
         'Day 2 — one zip per file per event, delivered via SFTP, originals archived to flexcount-save',
         3, 1, 'GM_TOTALS_CHECK', 24, GETUTCDATE(), GETUTCDATE());
    SET @id_CustomerWorkflowType = SCOPE_IDENTITY();
END

-- ── 2. Pewo_WorkflowStepDef ──────────────────────────────────────────────────
--
-- Step 1 READ_BLOB_ZIP:
--   sourceContainer = output-files (WISAppConstants.OutputFilesContainer)
--   Source files discovered inline via BlobContainerClient with prefix = {eventGuid}/
--   Filters for tar_itm_gm and tar_itm_prpc — no filePattern needed in config
--   Each file gets its own zip: TAR_ITM_GM_0421_...txt → TAR_ITM_GM_0421_...zip
--   Zips saved to flexcount-save (handoff for SFTP + permanent archive of zip)
--
-- Step 2 SFTP:
--   Reads staged: artifact_ref from READ_BLOB_ZIP
--   Delivers each zip individually to /www.data/target-ssh/nexgen via IFtpHelper.UploadFile
--   IFtpHelper appends WISAppConstants.InLocation (/in/) to remotePath internally
--   idCustomer injected at seed time from @id_Customer
--
-- Step 3 ARCHIVE:
--   Copies original .txt files from output-files/{eventGuid}/ to flexcount-save/{runId}/
--   Zips already in flexcount-save from step 1 — nothing extra
--   No deletion: eventGuid subfolder is unique per event, no reprocessing risk

MERGE dbo.Pewo_WorkflowStepDef AS target
USING (
    VALUES
        (@id_CustomerWorkflowType, 1, 'READ_BLOB_ZIP',
         'Read and Zip GM + PRPC Files (one zip per file)',
         '{"sourceContainer":"output-files","stagingContainer":"flexcount-save"}',
         3, 60, 1),
        (@id_CustomerWorkflowType, 2, 'SFTP',
         'Deliver Each Zip to TARGET SFTP',
         @SftpConfig,
         3, 120, 1),
        (@id_CustomerWorkflowType, 3, 'ARCHIVE',
         'Archive Original txt Files to flexcount-save',
         '{"sourceContainer":"output-files","archiveContainer":"flexcount-save"}',
         3, 60, 1)
) AS source (id_CustomerWorkflowType, Step_Order, Step_Kind, Step_Name, Config, Max_Attempts, Backoff_Seconds, is_Active)
ON  target.id_CustomerWorkflowType = source.id_CustomerWorkflowType
AND target.Step_Order = source.Step_Order
WHEN MATCHED THEN UPDATE SET
    Step_Kind = source.Step_Kind, Step_Name = source.Step_Name, Config = source.Config,
    Max_Attempts = source.Max_Attempts, Backoff_Seconds = source.Backoff_Seconds,
    is_Active = source.is_Active, last_updated_date = GETUTCDATE()
WHEN NOT MATCHED BY TARGET THEN INSERT
    (id_CustomerWorkflowType, Step_Order, Step_Kind, Step_Name, Config,
     Max_Attempts, Backoff_Seconds, is_Active, created_date, last_updated_date)
VALUES
    (source.id_CustomerWorkflowType, source.Step_Order, source.Step_Kind, source.Step_Name,
     source.Config, source.Max_Attempts, source.Backoff_Seconds, source.is_Active,
     GETUTCDATE(), GETUTCDATE());

-- ── 3. Pewo_Schedule ─────────────────────────────────────────────────────────
IF EXISTS (SELECT 1 FROM dbo.Pewo_Schedule WHERE id_CustomerWorkflowType = @id_CustomerWorkflowType)
BEGIN
    SELECT @id_Schedule = id_Schedule FROM dbo.Pewo_Schedule WHERE id_CustomerWorkflowType = @id_CustomerWorkflowType;
    UPDATE dbo.Pewo_Schedule
    SET    Schedule_Name = 'TARGET GM_PRC_DELIVERY Daily 8AM', Cron_Expression = '0 8 * * *',
           Timezone = 'UTC', is_Enabled = 1, last_updated_date = GETUTCDATE()
    WHERE  id_Schedule = @id_Schedule;
    -- Next_Run_At intentionally NOT updated — worker advances it at runtime
END
ELSE
BEGIN
    INSERT INTO dbo.Pewo_Schedule
        (id_CustomerWorkflowType, Schedule_Name, Cron_Expression, Timezone, Next_Run_At, Status, is_Enabled, created_date, last_updated_date)
    VALUES
        (@id_CustomerWorkflowType, 'TARGET GM_PRC_DELIVERY Daily 8AM', '0 8 * * *', 'UTC',
         DATEADD(DAY, 1, CAST(CAST(GETUTCDATE() AS DATE) AS DATETIME)) + '08:00:00',
         'ACTIVE', 1, GETUTCDATE(), GETUTCDATE());
    SET @id_Schedule = SCOPE_IDENTITY();
END

SELECT 'Pewo_CustomerWorkflowType' AS [Table], @id_CustomerWorkflowType AS [id], 'GM_PRC_DELIVERY' AS [Code];
SELECT 'Pewo_Schedule' AS [Table], @id_Schedule AS [id_Schedule], Cron_Expression, Next_Run_At, Status FROM dbo.Pewo_Schedule WHERE id_Schedule = @id_Schedule;
SELECT Step_Order, Step_Kind, Step_Name, LEFT(Config, 120) AS Config, Max_Attempts FROM dbo.Pewo_WorkflowStepDef WHERE id_CustomerWorkflowType = @id_CustomerWorkflowType ORDER BY Step_Order;
GO
