using Azure.Storage.Blobs;
using Domain.ApiModels.Pewo;
using Domain.Constants;
using Domain.Helpers.Interfaces;
using Domain.Services.Interfaces;
using Domain.Services.Interfaces.Pewo;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using SendGrid;
using SendGrid.Helpers.Mail;
using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using WS.FC.Dapper.Shared.DTOs.Pewo;

namespace Domain.Services.Pewo;

/// <summary>
/// All PEWO step implementations. Called directly in-process by PewoWorkerService.
/// PewoController exposes the same methods as HTTP endpoints for testing and manual ops.
///
/// Dependencies — ALL existing, no new packages:
///   ITotalsValidationService  — TOTALS_CHECK (ValidateNgen uses output-files/{eventGuid}/ internally)
///   IAzureBlobStorageHelper   — READ_BLOB_ZIP (DownloadFileBlob, UploadFileAsync), ARCHIVE, SFTP
///   IFtpHelper                — SFTP (UploadFile with SSH key auth to legacy SFTP server)
///   IConfiguration            — EMAIL/EMAIL_SUMMARY (SendGrid), blob connection string for listing
///   IPewoJobDataService       — EMAIL_SUMMARY (batch status)
///
/// NGen file location: output-files/{eventGuid}/TAR_ITM_GM_*  and  output-files/{eventGuid}/TAR_ITM_PRPC_*
/// These are automatically generated by the existing backend process and already present before TOTALS_CHECK runs.
/// </summary>
public class PewoStepService : IPewoStepService
{
    private readonly ITotalsValidationService  _totalsValidationService;
    private readonly IAzureBlobStorageHelper   _blobHelper;
    private readonly IFtpHelper                _ftpHelper;
    private readonly IPewoJobDataService       _pewoJobDataService;
    private readonly IConfiguration            _configuration;
    private readonly ILogger<PewoStepService>  _logger;

    // Cached blob connection string — same value TotalsValidationService uses
    private readonly string _blobConnectionString;

    public PewoStepService(
        ITotalsValidationService  totalsValidationService,
        IAzureBlobStorageHelper   blobHelper,
        IFtpHelper                ftpHelper,
        IPewoJobDataService       pewoJobDataService,
        IConfiguration            configuration,
        ILogger<PewoStepService>  logger)
    {
        _totalsValidationService = totalsValidationService;
        _blobHelper              = blobHelper;
        _ftpHelper               = ftpHelper;
        _pewoJobDataService      = pewoJobDataService;
        _configuration           = configuration;
        _logger                  = logger;
        _blobConnectionString    = configuration[WISAppConstants.VaultBlobKey];
    }

    // ── TOTALS_CHECK ──────────────────────────────────────────────────────────
    // Delegates to ITotalsValidationService.ValidateNgen(eventGuid).
    // That service already knows to look in output-files/{eventGuid}/ for the files.
    // No blob access needed here — ValidateNgen handles it internally.
    //
    // TODO (OPEN): Replace with HTTP call to dedicated TotalsValidation endpoint
    // once that separate API is built. Nothing else changes — step still
    // succeeds or fails the same way.

    public PewoStepResponse TotalsCheck(PewoStepRequest request)
    {
        _logger.LogInformation("[PEWO] TOTALS_CHECK RunId={RunId} Store={Store}",
            request.Id_WorkflowRun, request.Store_No);
        try
        {
            if (string.IsNullOrWhiteSpace(request.Event_Guid))
                return Fail("TOTALS_CHECK: Event_Guid is missing. Confirm event-close call included Event_Guid.");

            var result = _totalsValidationService.ValidateNgen(request.Event_Guid);

            if (!result.Success)
            {
                var errors = string.Join("; ", result.Messages
                    .Where(m => m.Status == "Error")
                    .Select(m => m.Step));
                _logger.LogWarning("[PEWO] TOTALS_CHECK RunId={RunId} FAILED: {Errors}",
                    request.Id_WorkflowRun, errors);
                return Fail($"TotalsCheck validation failed: {errors}");
            }

            var artifactRef = JsonSerializer.Serialize(new
            {
                totalQty = result.TotalQty,
                totalExt = result.TotalExt,
                eventGuid = request.Event_Guid
            });

            _logger.LogInformation("[PEWO] TOTALS_CHECK RunId={RunId} PASSED Qty={Qty} Ext={Ext}",
                request.Id_WorkflowRun, result.TotalQty, result.TotalExt);

            return Success(artifactRef);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[PEWO] TOTALS_CHECK RunId={RunId} exception", request.Id_WorkflowRun);
            return Fail($"Exception: {ex.Message}");
        }
    }

    // ── GET_EVENTS ────────────────────────────────────────────────────────────
    // MEO only — discovers files from blob storage by configured prefix.
    // STUB: full implementation deferred until MEO file location in blob confirmed.

    public async Task<PewoStepResponse> GetEventsAsync(PewoStepRequest request, CancellationToken cancellationToken)
    {
        _logger.LogInformation("[PEWO] GET_EVENTS RunId={RunId}", request.Id_WorkflowRun);
        try
        {
            if (!string.IsNullOrEmpty(request.Artifact_Ref) &&
                request.Artifact_Ref.StartsWith("discovered:", StringComparison.OrdinalIgnoreCase))
            {
                _logger.LogInformation("[PEWO] GET_EVENTS RunId={RunId} already discovered — skipping", request.Id_WorkflowRun);
                return Success(request.Artifact_Ref);
            }

            var config          = ParseConfig(request.Config);
            var sourceContainer = config.TryGetValue("sourceContainer", out var sc) ? sc : "fc-hold-target";
            var filePattern     = config.TryGetValue("filePattern", out var fp) ? fp : string.Empty;

            var container = new BlobContainerClient(_blobConnectionString, sourceContainer);
            var discovered = new List<string>();

            await foreach (var blobItem in container.GetBlobsAsync(prefix: filePattern,
                cancellationToken: cancellationToken))
            {
                discovered.Add(blobItem.Name);
            }

            if (!discovered.Any())
            {
                _logger.LogInformation("[PEWO] GET_EVENTS RunId={RunId} no blobs found in {Container}/{Pattern}",
                    request.Id_WorkflowRun, sourceContainer, filePattern);
                return Success($"discovered:0:{DateTime.UtcNow:yyyyMMdd}");
            }

            // Record discovered files as WorkflowRunEvent metadata
            await _pewoJobDataService.CreateWorkflowRunEventAsync(
                request.Id_WorkflowRun,
                null, null, null, null, null,
                null, null, null, DateTime.UtcNow,
                JsonSerializer.Serialize(discovered),
                cancellationToken);

            _logger.LogInformation("[PEWO] GET_EVENTS RunId={RunId} discovered {Count} blobs",
                request.Id_WorkflowRun, discovered.Count);

            return Success($"discovered:{discovered.Count}:{DateTime.UtcNow:yyyyMMdd}");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[PEWO] GET_EVENTS RunId={RunId} exception", request.Id_WorkflowRun);
            return Fail($"Exception: {ex.Message}");
        }
    }

    // ── TRANSFORM ─────────────────────────────────────────────────────────────
    // MEO only — file conversion (EBCDIC for ICNTS, ASCII-only for CPINV/CTL).
    // Uses existing EBCDICFileHelper. STUB for initial NGen delivery.
    // NGen files require NO conversion — this step is not in GM_PRC_DELIVERY seed.

    public async Task<PewoStepResponse> TransformAsync(PewoStepRequest request, CancellationToken cancellationToken)
    {
        _logger.LogInformation("[PEWO] TRANSFORM RunId={RunId}", request.Id_WorkflowRun);
        try
        {
            // TODO (MEO): Implement per-file conversion:
            //   icnts.dat  → UTF-8 → ASCII → EBCDIC (EBCDICFileHelper)
            //   cpinv.dat  → UTF-8 → ASCII only
            //   T{MMDDYY}.ctl → UTF-8 → ASCII only
            //   T{MMDDYY}.xlsx → generated from CTL (Excel conversion)
            // Blocked on MEO file location in blob storage being confirmed.
            // EBCDICFileHelper.cs already exists in Domain.Helpers for EBCDIC conversion.

            _logger.LogWarning("[PEWO] TRANSFORM RunId={RunId} — stub implementation. MEO conversion pending.",
                request.Id_WorkflowRun);

            return await Task.FromResult(Success($"transform-stub:{request.Id_WorkflowRun}:{DateTime.UtcNow:O}"));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[PEWO] TRANSFORM RunId={RunId} exception", request.Id_WorkflowRun);
            return Fail($"Exception: {ex.Message}");
        }
    }

    // ── READ_BLOB_ZIP ─────────────────────────────────────────────────────────
    // NGen (GM_PRC_DELIVERY):
    //   Source: output-files/{eventGuid}/TAR_ITM_GM_0421_20250813_143022.txt
    //           output-files/{eventGuid}/TAR_ITM_PRPC_0421_20250813_143022.txt
    //   Each file gets its own individual zip with the same name but .zip extension.
    //   Zip uploaded to flexcount-save (handoff for SFTP + permanent archive of zip).
    //   Artifact_Ref: staged:TAR_ITM_GM_0421_...zip,TAR_ITM_PRPC_0421_...zip
    //
    // This exactly replicates post-nexgen-gm-file and post-nexgen-prpc-file scripts:
    //   7z a $POSTFN $FILETOZIP  (one zip per file, zip name = source name + .zip)
    //   cp -p $POSTFN $SAVEDIR   (zip saved to flexcount-save)
    //
    // Idempotent: same zip names per event run; UploadFileAsync overwrites on retry.

    public async Task<PewoStepResponse> ReadBlobZipAsync(PewoStepRequest request, CancellationToken cancellationToken)
    {
        _logger.LogInformation("[PEWO] READ_BLOB_ZIP RunId={RunId} EventGuid={Guid}",
            request.Id_WorkflowRun, request.Event_Guid);
        try
        {
            if (!string.IsNullOrEmpty(request.Artifact_Ref) &&
                request.Artifact_Ref.StartsWith("staged:", StringComparison.OrdinalIgnoreCase))
            {
                _logger.LogInformation("[PEWO] READ_BLOB_ZIP RunId={RunId} already staged — skipping",
                    request.Id_WorkflowRun);
                return Success(request.Artifact_Ref);
            }

            if (string.IsNullOrWhiteSpace(request.Event_Guid))
                return Fail("READ_BLOB_ZIP: Event_Guid missing — cannot locate source files.");

            var config          = ParseConfig(request.Config);
            var sourceContainer = config.TryGetValue("sourceContainer", out var sc)
                ? sc : WISAppConstants.OutputFilesContainer;
            var stagingContainer = config.TryGetValue("stagingContainer", out var stg)
                ? stg : "flexcount-save";

            // Discover source files in output-files/{eventGuid}/ — same pattern as TotalsValidationService
            var blobContainer = new BlobContainerClient(_blobConnectionString, sourceContainer);
            var prefix        = request.Event_Guid + "/";
            var sourceFiles   = new List<string>();

            await foreach (var blobItem in blobContainer.GetBlobsAsync(prefix: prefix,
                cancellationToken: cancellationToken))
            {
                var name = blobItem.Name;
                if (name.Contains("tar_itm_gm",   StringComparison.OrdinalIgnoreCase) ||
                    name.Contains("tar_itm_prpc",  StringComparison.OrdinalIgnoreCase))
                {
                    sourceFiles.Add(name);
                }
            }

            if (!sourceFiles.Any())
                return Fail($"READ_BLOB_ZIP: No GM or PRPC files found in '{sourceContainer}/{prefix}'. " +
                            "Confirm backend process generated the files for this event.");

            var zipsCreated = new List<string>();

            foreach (var blobPath in sourceFiles)
            {
                var sourceFileName = Path.GetFileName(blobPath);
                var zipFileName    = Path.ChangeExtension(sourceFileName, ".zip");

                // DownloadFileBlob(container, blobPath) — first param is container per impl convention
                var fileStream = await _blobHelper.DownloadFileBlob(sourceContainer, blobPath);

                if (fileStream == null || fileStream.Length == 0)
                    return Fail($"READ_BLOB_ZIP: Source blob '{blobPath}' downloaded empty.");

                // Create individual in-memory zip — same as 7z a $POSTFN $FILETOZIP in the script
                using var zipStream = new MemoryStream();
                using (var archive = new ZipArchive(zipStream, ZipArchiveMode.Create, leaveOpen: true))
                {
                    var entry = archive.CreateEntry(sourceFileName, CompressionLevel.Optimal);
                    await using var entryStream = entry.Open();
                    fileStream.Position = 0;
                    await fileStream.CopyToAsync(entryStream, cancellationToken);
                }

                // Upload zip to flexcount-save — same as cp -p $POSTFN $SAVEDIR in the script
                zipStream.Position = 0;
                await _blobHelper.UploadFileAsync(stagingContainer, zipStream, zipFileName);
                zipsCreated.Add(zipFileName);

                _logger.LogInformation("[PEWO] READ_BLOB_ZIP RunId={RunId} created {Zip} in {Container}",
                    request.Id_WorkflowRun, zipFileName, stagingContainer);
            }

            var artifactRef = $"staged:{string.Join(",", zipsCreated)}";
            return Success(artifactRef);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[PEWO] READ_BLOB_ZIP RunId={RunId} exception", request.Id_WorkflowRun);
            return Fail($"Exception: {ex.Message}");
        }
    }

    // ── SFTP ──────────────────────────────────────────────────────────────────
    // Delivers each individual zip from flexcount-save to TARGET SFTP via IFtpHelper.UploadFile.
    // IFtpHelper.UploadFile uses SSH key authentication (LegacyUserName/HostName/Port/SSHKey from Key Vault).
    // IFtpHelper requires FileStream — temp file is written, delivered, then deleted.
    // Constructs path: legacyLocation + WISAppConstants.InLocation + fileName
    //   e.g. /www.data/target-ssh/nexgen/in/TAR_ITM_GM_0421_...zip
    //
    // This matches the manual script: mv $POSTFN $POSTDIR/. (delivers to nexgen directory).
    //
    // Idempotent: artifact_ref "sftp:delivered:" guard prevents re-delivery on retry.

    public async Task<PewoStepResponse> SftpAsync(PewoStepRequest request, CancellationToken cancellationToken)
    {
        _logger.LogInformation("[PEWO] SFTP RunId={RunId}", request.Id_WorkflowRun);
        try
        {
            if (!string.IsNullOrEmpty(request.Artifact_Ref) &&
                request.Artifact_Ref.StartsWith("sftp:delivered:", StringComparison.OrdinalIgnoreCase))
            {
                _logger.LogInformation("[PEWO] SFTP RunId={RunId} already delivered — skipping", request.Id_WorkflowRun);
                return Success(request.Artifact_Ref);
            }

            var config           = ParseConfig(request.Config);
            var remotePath       = config.TryGetValue("remotePath", out var rp) ? rp : string.Empty;
            var stagingContainer = config.TryGetValue("stagingContainer", out var stg) ? stg : "flexcount-save";

            if (string.IsNullOrWhiteSpace(remotePath))
                return Fail("SFTP: 'remotePath' missing from step config.");

            // Parse staged: artifact_ref from READ_BLOB_ZIP
            var priorRef = request.Artifact_Ref ?? string.Empty;
            if (!priorRef.StartsWith("staged:", StringComparison.OrdinalIgnoreCase))
                return Fail("SFTP: Expected artifact_ref in 'staged:' format from READ_BLOB_ZIP step. " +
                            "Ensure READ_BLOB_ZIP ran and succeeded before SFTP.");

            var zipNames = priorRef["staged:".Length..]
                .Split(',', StringSplitOptions.RemoveEmptyEntries)
                .Select(z => z.Trim())
                .ToList();

            if (!zipNames.Any())
                return Fail("SFTP: No zip names found in staged: artifact_ref.");

            var deliveredFiles = new List<string>();

            foreach (var zipName in zipNames)
            {
                string? tempPath = null;
                try
                {
                    // Download zip from flexcount-save
                    var zipStream = await _blobHelper.DownloadFileBlob(stagingContainer, zipName);

                    if (zipStream == null || zipStream.Length == 0)
                        return Fail($"SFTP: Staging zip '{zipName}' not found or empty in {stagingContainer}.");

                    // IFtpHelper.UploadFile requires FileStream — write to temp, deliver, clean up
                    tempPath = Path.Combine(Path.GetTempPath(), $"pewo_{request.Id_WorkflowRun}_{zipName}");
                    zipStream.Position = 0;

                    await using (var fs = new FileStream(tempPath, FileMode.Create, FileAccess.Write))
                        await zipStream.CopyToAsync(fs, cancellationToken);

                    string uploadResult;
                    await using (var fileStream = new FileStream(tempPath, FileMode.Open, FileAccess.Read))
                        uploadResult = await _ftpHelper.UploadFile(fileStream, zipName, remotePath, _logger);

                    if (uploadResult != MessageConstants.Uploaded)
                        return Fail($"SFTP upload failed for '{zipName}': {uploadResult}");

                    _logger.LogInformation("[PEWO] SFTP RunId={RunId} delivered {File} to {Path}",
                        request.Id_WorkflowRun, zipName, remotePath);
                    deliveredFiles.Add(zipName);
                }
                finally
                {
                    try
                    {
                        if (tempPath != null && File.Exists(tempPath))
                            File.Delete(tempPath);
                    }
                    catch (Exception cleanupEx)
                    {
                        _logger.LogWarning(cleanupEx, "[PEWO] SFTP failed to delete temp file {Path}", tempPath);
                    }
                }
            }

            return Success($"sftp:delivered:{remotePath}:{string.Join(",", deliveredFiles)}");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[PEWO] SFTP RunId={RunId} exception", request.Id_WorkflowRun);
            return Fail($"Exception: {ex.Message}");
        }
    }

    // ── ARCHIVE ───────────────────────────────────────────────────────────────
    // Copies original .txt source files from output-files/{eventGuid}/ to flexcount-save.
    // Zips are already in flexcount-save from READ_BLOB_ZIP — nothing extra needed for zips.
    //
    // NO DELETION: files live in output-files/{eventGuid}/ which is unique per event.
    // There is zero risk of reprocessing the same file on a future run.
    // Deleting is unnecessary and risks data loss on investigation.
    //
    // This matches: mv $WRKCPY $SAVEDIR/. in the manual script (archives original .txt).
    //
    // Idempotent: artifact_ref "archived:" guard + UploadFileAsync overwrites on retry.

    public async Task<PewoStepResponse> ArchiveAsync(PewoStepRequest request, CancellationToken cancellationToken)
    {
        _logger.LogInformation("[PEWO] ARCHIVE RunId={RunId} EventGuid={Guid}",
            request.Id_WorkflowRun, request.Event_Guid);
        try
        {
            if (!string.IsNullOrEmpty(request.Artifact_Ref) &&
                request.Artifact_Ref.StartsWith("archived:", StringComparison.OrdinalIgnoreCase))
            {
                _logger.LogInformation("[PEWO] ARCHIVE RunId={RunId} already archived — skipping", request.Id_WorkflowRun);
                return Success(request.Artifact_Ref);
            }

            if (string.IsNullOrWhiteSpace(request.Event_Guid))
                return Fail("ARCHIVE: Event_Guid missing — cannot locate source files.");

            var config           = ParseConfig(request.Config);
            var sourceContainer  = config.TryGetValue("sourceContainer", out var sc)
                ? sc : WISAppConstants.OutputFilesContainer;
            var archiveContainer = config.TryGetValue("archiveContainer", out var ac)
                ? ac : "flexcount-save";

            // Discover source files in output-files/{eventGuid}/
            var blobContainer = new BlobContainerClient(_blobConnectionString, sourceContainer);
            var prefix        = request.Event_Guid + "/";
            var sourceFiles   = new List<string>();

            await foreach (var blobItem in blobContainer.GetBlobsAsync(prefix: prefix,
                cancellationToken: cancellationToken))
            {
                var name = blobItem.Name;
                if (name.Contains("tar_itm_gm",   StringComparison.OrdinalIgnoreCase) ||
                    name.Contains("tar_itm_prpc",  StringComparison.OrdinalIgnoreCase))
                {
                    sourceFiles.Add(name);
                }
            }

            if (!sourceFiles.Any())
            {
                // Source files may already be gone if this is a retry after partial success.
                // Check if archive already has them — idempotency path.
                _logger.LogWarning("[PEWO] ARCHIVE RunId={RunId} no source files found in {Container}/{Prefix}. " +
                    "Files may already be archived from a previous attempt.",
                    request.Id_WorkflowRun, sourceContainer, prefix);
                return Success($"archived:0:{request.Event_Guid}");
            }

            var archivedCount = 0;

            foreach (var blobPath in sourceFiles)
            {
                var sourceFileName  = Path.GetFileName(blobPath);
                // Archive path: flexcount-save/{runId}/{filename}
                var archiveBlobName = $"{request.Id_WorkflowRun}/{sourceFileName}";

                var fileStream = await _blobHelper.DownloadFileBlob(sourceContainer, blobPath);

                if (fileStream == null || fileStream.Length == 0)
                {
                    _logger.LogWarning("[PEWO] ARCHIVE RunId={RunId} blob {Path} downloaded empty — skipping",
                        request.Id_WorkflowRun, blobPath);
                    continue;
                }

                fileStream.Position = 0;
                await _blobHelper.UploadFileAsync(archiveContainer, fileStream, archiveBlobName);
                archivedCount++;

                _logger.LogInformation("[PEWO] ARCHIVE RunId={RunId} archived {Source} → {Dest}",
                    request.Id_WorkflowRun, blobPath, $"{archiveContainer}/{archiveBlobName}");
            }

            // Note: Zips in flexcount-save are already the archive copy — no action needed.
            // Note: Source originals in output-files/{eventGuid}/ are NOT deleted.
            //       The eventGuid subfolder makes them unique per event — no reprocessing risk.

            return Success($"archived:{archivedCount}:{request.Event_Guid}");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[PEWO] ARCHIVE RunId={RunId} exception", request.Id_WorkflowRun);
            return Fail($"Exception: {ex.Message}");
        }
    }

    // ── EMAIL ─────────────────────────────────────────────────────────────────
    // Per-event/run notification email via SendGrid.
    // Same double-indirection as existing SendEmailService:
    //   config[config[SendGridEmailKey]] → API key value
    //   config[config[SendGridEmail]]    → from address value
    // Idempotent: "notified:" artifact_ref guard.

    public async Task<PewoStepResponse> EmailAsync(PewoStepRequest request, CancellationToken cancellationToken)
    {
        _logger.LogInformation("[PEWO] EMAIL RunId={RunId}", request.Id_WorkflowRun);
        try
        {
            if (!string.IsNullOrEmpty(request.Artifact_Ref) &&
                request.Artifact_Ref.StartsWith("notified:", StringComparison.OrdinalIgnoreCase))
            {
                _logger.LogInformation("[PEWO] EMAIL RunId={RunId} already sent — skipping", request.Id_WorkflowRun);
                return Success(request.Artifact_Ref);
            }

            var config     = ParseConfig(request.Config);
            var subject    = config.TryGetValue("subject", out var s) ? s : "PEWO — Workflow Completed";
            var recipients = GetRecipients(config);

            if (!recipients.Any())
                return Fail("EMAIL: No recipients configured in step Config JSON.");

            var body = BuildNotificationEmailBody(request.Id_WorkflowRun, request.Store_No, request.Event_Guid);
            await SendEmailAsync(recipients, subject, body, cancellationToken);

            _logger.LogInformation("[PEWO] EMAIL RunId={RunId} sent to {Count} recipients",
                request.Id_WorkflowRun, recipients.Count);

            return Success($"notified:{DateTime.UtcNow:O}");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[PEWO] EMAIL RunId={RunId} exception", request.Id_WorkflowRun);
            return Fail($"Exception: {ex.Message}");
        }
    }

    // ── EMAIL_SUMMARY ─────────────────────────────────────────────────────────
    // Consolidated batch ack email for GM_PRC_DELIVERY fan-out batch.
    // Retry/backoff acts as wait gate: returns failure while batch still active,
    // forcing the scheduler to retry until all child runs are terminal.
    // On last retry (or batch fully terminal), sends whatever state exists.
    // Idempotent: "summary-sent:" artifact_ref guard.

    public async Task<PewoStepResponse> EmailSummaryAsync(PewoStepRequest request, CancellationToken cancellationToken)
    {
        _logger.LogInformation("[PEWO] EMAIL_SUMMARY RunId={RunId}", request.Id_WorkflowRun);
        try
        {
            if (!string.IsNullOrEmpty(request.Artifact_Ref) &&
                request.Artifact_Ref.StartsWith("summary-sent:", StringComparison.OrdinalIgnoreCase))
            {
                _logger.LogInformation("[PEWO] EMAIL_SUMMARY RunId={RunId} already sent — skipping",
                    request.Id_WorkflowRun);
                return Success(request.Artifact_Ref);
            }

            var config                = ParseConfig(request.Config);
            var batchWorkflowTypeCode = config.TryGetValue("batchWorkflowTypeCode", out var bwt)
                ? bwt : "GM_PRC_DELIVERY";
            var subject    = config.TryGetValue("subject", out var s)
                ? s : "TARGET GM + PRPC Delivery Summary";
            var recipients = GetRecipients(config);

            if (!recipients.Any())
                return Fail("EMAIL_SUMMARY: No recipients configured in step Config JSON.");

            var todayKey  = DateTime.UtcNow.ToString("yyyy-MM-dd");
            var batchRuns = await _pewoJobDataService.GetBatchRunStatusAsync(
                batchWorkflowTypeCode, todayKey, cancellationToken);

            var stillActive      = batchRuns.Count(r => r.Status == "PENDING" || r.Status == "RUNNING");
            var maxAttemptsReached = request.Attempts >= request.Max_Attempts;

            if (stillActive > 0 && !maxAttemptsReached)
            {
                _logger.LogInformation(
                    "[PEWO] EMAIL_SUMMARY RunId={RunId} batch not settled yet — {Active}/{Total} still active (attempt {A}/{Max})",
                    request.Id_WorkflowRun, stillActive, batchRuns.Count, request.Attempts, request.Max_Attempts);
                return Fail($"Batch not fully terminal — {stillActive} of {batchRuns.Count} still in progress. Will retry.");
            }

            var body = BuildSummaryEmailBody(todayKey, batchRuns, stillActive > 0);
            await SendEmailAsync(recipients, subject, body, cancellationToken);

            _logger.LogInformation("[PEWO] EMAIL_SUMMARY RunId={RunId} sent for batch {Key} ({Count} events)",
                request.Id_WorkflowRun, todayKey, batchRuns.Count);

            return Success($"summary-sent:{todayKey}:{batchRuns.Count}events");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "[PEWO] EMAIL_SUMMARY RunId={RunId} exception", request.Id_WorkflowRun);
            return Fail($"Exception: {ex.Message}");
        }
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private async Task SendEmailAsync(List<string> recipients, string subject, string htmlBody,
        CancellationToken cancellationToken)
    {
        var apiKey      = _configuration[_configuration[WISAppConstants.SendGridEmailKey]];
        var fromAddress = _configuration[_configuration[WISAppConstants.SendGridEmail]];

        if (string.IsNullOrWhiteSpace(apiKey) || string.IsNullOrWhiteSpace(fromAddress))
            throw new InvalidOperationException(
                "SendGrid configuration missing. Check KeyVaultSettings:SendGridEmailKey and KeyVaultSettings:SendGridEmail.");

        var client  = new SendGridClient(apiKey);
        var from    = new EmailAddress(fromAddress, "FlexCount PEWO");
        var toList  = recipients.Select(r => new EmailAddress(r.Trim())).ToList();
        var message = MailHelper.CreateSingleEmailToMultipleRecipients(from, toList, subject, htmlBody, htmlBody);

        var response = await client.SendEmailAsync(message, cancellationToken);

        if ((int)response.StatusCode >= 400)
        {
            var body = await response.Body.ReadAsStringAsync(cancellationToken);
            throw new InvalidOperationException($"SendGrid returned {(int)response.StatusCode}: {body}");
        }
    }

    private static string BuildNotificationEmailBody(int runId, string? storeNo, string? eventGuid) =>
        $@"<html><body>
<h2>FlexCount PEWO — Workflow Completed</h2>
<table border='1' cellpadding='6'>
  <tr><td><strong>Run ID</strong></td><td>{runId}</td></tr>
  <tr><td><strong>Store</strong></td><td>{storeNo ?? "—"}</td></tr>
  <tr><td><strong>Event GUID</strong></td><td>{eventGuid ?? "—"}</td></tr>
  <tr><td><strong>Completed At (UTC)</strong></td><td>{DateTime.UtcNow:u}</td></tr>
</table>
<p>Post-event NGen files have been validated, zipped, delivered via SFTP, and archived.</p>
</body></html>";

    private static string BuildSummaryEmailBody(
        string todayKey, List<BatchRunStatusDto> batch, bool hasStillActive)
    {
        var sb = new StringBuilder();
        sb.Append("<html><body>");
        sb.Append($"<h2>TARGET GM + PRPC Delivery Summary — {todayKey}</h2>");

        if (hasStillActive)
            sb.Append("<p><strong>Note:</strong> Some events were still in progress when this summary was sent (retry limit reached).</p>");

        if (!batch.Any())
        {
            sb.Append("<p>No GM/PRPC deliveries were due today.</p>");
        }
        else
        {
            sb.Append("<table border='1' cellpadding='6'>");
            sb.Append("<tr><th>Run ID</th><th>Store</th><th>Event Date</th><th>Status</th><th>Details</th></tr>");
            foreach (var row in batch.OrderBy(b => b.Store_No))
            {
                sb.Append($"<tr><td>{row.Id_WorkflowRun}</td><td>{row.Store_No}</td>" +
                          $"<td>{row.Event_Date:yyyy-MM-dd}</td><td>{row.Status}</td><td>{row.Reason ?? "—"}</td></tr>");
            }
            sb.Append("</table>");
        }

        sb.Append("</body></html>");
        return sb.ToString();
    }

    private static List<string> GetRecipients(Dictionary<string, string> config)
    {
        if (!config.TryGetValue("recipients", out var r) || string.IsNullOrWhiteSpace(r))
            return new List<string>();
        return r.Split(',', StringSplitOptions.RemoveEmptyEntries)
                .Select(x => x.Trim())
                .Where(x => x.Length > 0)
                .ToList();
    }

    private static Dictionary<string, string> ParseConfig(string? configJson)
    {
        if (string.IsNullOrWhiteSpace(configJson))
            return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        try
        {
            using var doc = JsonDocument.Parse(configJson);
            var dict = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var prop in doc.RootElement.EnumerateObject())
            {
                dict[prop.Name] = prop.Value.ValueKind == JsonValueKind.String
                    ? prop.Value.GetString() ?? string.Empty
                    : prop.Value.ToString();
            }
            return dict;
        }
        catch
        {
            return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        }
    }

    private static PewoStepResponse Success(string? artifactRef) =>
        new() { Success = true, Artifact_Ref = artifactRef };

    private static PewoStepResponse Fail(string reason) =>
        new() { Success = false, Failure_Details = reason };
}
